// Available fonts for the editor
// These are loaded via Google Fonts in index.html
const FONTS = [
  // System fonts
  "Arial",
  "Helvetica",
  "Times New Roman",
  "Georgia",
  "Courier New",
  "Verdana",
  // Google Fonts
  "Abril Fatface",
  "Alegreya",
  "Alfa Slab One",
  "Alumni Sans Collegiate One",
  "Amatic SC",
  "Anton",
  "Antonio",
  "Archivo Narrow",
  "Arimo",
  "Asap",
  "Barlow Condensed",
  "Barriecito",
  "Bebas Neue",
  "Berkshire Swash",
  "Bungee",
  "Cabin Sketch",
  "Charis SIL",
  "Codystar",
  "Comic Relief",
  "Courier Prime",
  "Creepster",
  "Crimson Text",
  "DM Sans",
  "Dancing Script",
  "Domine",
  "Eater",
  "Exo",
  "Figtree",
  "Frijole",
  "Glass Antiqua",
  "Grand Hotel",
  "Great Vibes",
  "Homemade Apple",
  "IBM Plex Mono",
  "Imbue",
  "Inconsolata",
  "Indie Flower",
  "Instrument Serif",
  "Inter",
  "Inter Tight",
  "Jacquard 12",
  "Jacquard 24",
  "Josefin Sans",
  "Kranky",
  "Lacquer",
  "Lato",
  "League Gothic",
  "League Spartan",
  "Leckerli One",
  "Lemon",
  "Lemonada",
  "Libre Baskerville",
  "Libre Franklin",
  "Limelight",
  "Lobster",
  "Londrina Shadow",
  "Lora",
  "Luckiest Guy",
  "Manrope",
  "Matemasie",
  "Merriweather",
  "Metal Mania",
  "Monoton",
  "Montserrat",
  "Mountains of Christmas",
  "Noto Sans",
  "Oi",
  "Open Sans",
  "Orbitron",
  "Oswald",
  "PT Serif",
  "Pacifico",
  "Parkinsans",
  "Patrick Hand",
  "Pattaya",
  "Permanent Marker",
  "Plaster",
  "Playfair Display",
  "Pompiere",
  "Poppins",
  "Quicksand",
  "Racing Sans One",
  "Raleway",
  "Roboto",
  "Roboto Condensed",
  "Roboto Slab",
  "Rock Salt",
  "Rye",
  "STIX Two Text",
  "Sacramento",
  "Sansita Swashed",
  "Satisfy",
  "Shrikhand",
  "Tiny5",
  "Unbounded",
  "Underdog",
  // Additional popular fonts
  "Advent Pro",
  "Audiowide",
  "Bangers",
  "Black Ops One",
  "Bree Serif",
  "Cabin",
  "Caveat",
  "Chakra Petch",
  "Cinzel",
  "Comfortaa",
  "Concert One",
  "Cormorant Garamond",
  "Dela Gothic One",
  "EB Garamond",
  "Fjalla One",
  "Fredoka",
  "Gochi Hand",
  "Jost",
  "Kanit",
  "Kaushan Script",
  "Kalam",
  "Lexend",
  "Lilita One",
  "Merriweather Sans",
  "Nunito",
  "Nunito Sans",
  "Onest",
  "Outfit",
  "Passion One",
  "Patua One",
  "Play",
  "Poetsen One",
  "Press Start 2P",
  "Righteous",
  "Rubik",
  "Russo One",
  "Shadows Into Light",
  "Sigmar One",
  "Silkscreen",
  "Source Code Pro",
  "Source Sans 3",
  "Space Grotesk",
  "Space Mono",
  "Special Elite",
  "Staatliches",
  "Teko",
  "Titan One",
  "Ubuntu",
  "Ultra",
  "Work Sans",
  "Yellowtail",
  "Zeyada",
];

export default FONTS;
